-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgdCkBSQ+yRcltlgE1
8RGIukHuVYXDJygrae14QaG3WtGgCgYIKoZIzj0DAQehRANCAAQGjqOvjyj9TNrH
T1wKW44zqaKfsbXZOcBMWTGQCYRU4EUQ3UUM84PmmxdycDA+pQJ0XFj5KK0NeJwS
uqgKIgFd
-----END PRIVATE KEY-----